### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by toxinu** [toxinu/pyhn#22]
Some people emails me about Windows support.
I don't have any Windows available to test it, so if you have Python skills, your help is welcome.

But I clearly won't support Windows by myself.
By the way, I think there are no many changes to do to get it working.

**Comment by with0out** [comment]
Well, Windows 7 64bit, python 2.7.11,  *pip install pyhn* didn't produce executable file.

**Comment by socketubs** [comment]
@with0out Sorry to hear that. You are welcome to contribute to windows support. :cry:
