### ISSUE TITLE
Nothing shown in columns SCORE & COMMENTS

### ISSUE THREAD

**Issue by DotComing** [toxinu/pyhn#40]
![image](https://cloud.githubusercontent.com/assets/7887395/17727152/039961d0-648a-11e6-9b75-af0f323cf360.png)

Columns SCORE & COMMENTS show nothing on the right when running pyhn.

#### FYI
- Mac OS 10.11.6
- Python 2.7.10
- pyhn 0.3.7, Latest, install by `git clone XXX.git` & `sudo python setup.py install`

**Comment by toxinu** [comment]
Can you test with `0.3.8` from Pypi or just `master` branch please.

**Comment by DotComing** [comment]
Nice! It has been fixed. Thanks.
